module.exports={
    port:8081,
    db:{
        database:'occupancy-chart',
        user:'root',
        password:'',
        options:{
            dialect:'mysql',
            host:'localhost'
        }
    },
    authentication:{
        jwtSecret:process.env.JWT_SECRET||'secret'
    }
}